import { Router } from 'express';
import healthRoutes from './health.routes.js';
import authRoutes from '../modules/auth/auth.routes.js';
import userRoutes from '../modules/users/user.routes.js';
import profileRoutes from '../modules/profiles/profile.routes.js';
import careerRoutes from '../modules/careers/career.routes.js';
import skillRoutes from '../modules/skills/skill.routes.js';
import courseRoutes from '../modules/courses/course.routes.js';
import institutionRoutes from '../modules/institutions/institution.routes.js';
import skillIntelligenceRoutes from '../modules/skills/skill-intelligence.routes.js';
import recommendationRoutes from '../modules/recommendations/recommendation.routes.js';
import pathwayRoutes from '../modules/pathways/pathway.routes.js';
import eligibilityRoutes from '../modules/eligibility/eligibility.routes.js';
import { opportunityRequirementRoutes, adminOpportunityRequirementRoutes } from '../modules/eligibility/opportunity-requirement.routes.js';
import opportunityRoutes from '../modules/opportunities/opportunity.routes.js';
import assistantRoutes from '../modules/assistant/assistant.routes.js';
import { adminIngestionRoutes } from '../modules/ingestion/ingestion.routes.js';

const router = Router();
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/profiles', profileRoutes);
router.use('/careers', careerRoutes);
router.use('/skills', skillIntelligenceRoutes);
router.use('/skills', skillRoutes);
router.use('/courses', courseRoutes);
router.use('/institutions', institutionRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/pathways', pathwayRoutes);
router.use('/eligibility', eligibilityRoutes);
router.use('/opportunities', opportunityRoutes);
router.use('/assistant', assistantRoutes);
router.use('/opportunities', opportunityRequirementRoutes);
router.use('/admin/opportunities', adminOpportunityRequirementRoutes);
router.use('/admin', adminIngestionRoutes);
export default router;
